### ISSUE TITLE
shell script not quite right

### ISSUE THREAD

**Issue by brunov25** [rolfschr/GSWL-private-empty#1]
the last two commands in the proposed script will not work as is because the files referred to are still in a subdirectory at that point

**Comment by rolfschr** [comment]
Hi Bruno,

thanks for opening an issue. Could you elaborate a bit more: which script, which files, which subdirectory? Thanks!

**Comment by brunov25** [comment]
oh, i should have specified i am talking about the script on readme.md of this git project directory

https://github.com/rolfschr/GSWL-private-empty/blob/master/README.md

**Comment by rolfschr** [comment]
Ok, well it works fine for me. Did you forget the `cd $MYDIR` be chance?

**Comment by brunov25** [comment]
ok i think i see the problem:

the line "mv GSWL-private-empty $MYDIR"  on my version of bash moves the subdirectory GSWL-private-empty as a unit into $MYDIR ... not the content of that subdirectory

so when I cd into it in the next line, the files are not there, they are in a subdirectory called GSWL-private-empty

this is not a big deal ...i just wanted to leave a note in case others found the same minor annoyance

a simple solution is to change "mv GSWL-private-empty $MYDIR" to 
mv GSWL-private-empty/\* $MYDIR; rmdir GSWL-private-empty

**Comment by rolfschr** [comment]
Ah, ok, well that problem only occurs if the folder exist already, otherwise `mv` will rename as intended. Thanks for reporting.
